name: Cypress CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
        node: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run test:e2e:ci
        env:
          GITHUB_TOKEN: ${{ secrets.CYPRESS_GITHUB_TOKEN }}
