version: "3.8"

services:
  APL-Server:
    image: oven/bun:1
    container_name: apl-server
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "11612:3000"
    environment:
      - DB_PATH=/data/prod.db
    command: bun run start
    networks:
      - chromanet

networks:
  chromanet:
    external: true

volumes:
  elysia-db:
    driver: local
