name: Deploy Docker Container

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch (adjust for your repo)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH to server and restart Docker container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/aloo/Server/AutoProgressLog/apl-server  # Ensure you are in the correct directory
          git pull origin main  # Pull the latest code from the main branch
          docker-compose down  # Stop and remove the existing container
          docker-compose up -d  # Rebuild and restart the container in detached mode
