name: Release APL

on:
  push:
    branches:
      - main  # Adjust this to match your branch, usually 'main' or 'master'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust the Node.js version as needed

    - name: Install dependencies
      run: |
        cd apl-frontend
        npm install

    - name: Get version from package.json
      id: version
      run: |
        cd apl-frontend
        VERSION=$(node -p "require('./package.json').version")
        echo "Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Git tag for version
      run: |
        git tag $VERSION
        git push origin $VERSION

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: AutoProgressLog v${{ env.VERSION }}
        tag: ${{ env.VERSION }}
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          apl-frontend/release/**/*.exe    # Adjust to your actual build output files
          apl-frontend/release/**/*.dmg
          apl-frontend/release/**/*.AppImage
          apl-frontend/release/**/*.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}